<?php
/**
 * @file
 * Code for the the subjects feature.
 */
 
include_once('vih_subjects.features.inc');

/**
 * Implements hook_migrate_api().
 *
 * @return array
 */
function vih_subjects_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'VIHSubjectsNode' => array('class_name' => 'VIHSubjectsNode'),
      'VIHSubjectsPackageTaxonomy' => array('class_name' => 'VIHSubjectsPackageTaxonomy'),
    ),
  );
  return $api;
}